<a href="https://colab.research.google.com/github/jclark7729/athletic_sales_analysis/blob/main/athletic_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# Import Libraries and Dependencies
import pandas as pd

### 1. Combine and Clean the Data
#### Import CSVs

In [24]:
from google.colab import files
uploaded = files.upload()

Saving athletic_sales_2020.csv to athletic_sales_2020 (2).csv
Saving athletic_sales_2021.csv to athletic_sales_2021 (2).csv

In [25]:
# Save the uploaded files to the current working directory
for filename, content in uploaded.items():
  with open(filename, 'wb') as f:
    f.write(content)
    f.close()

In [27]:
# Read the CSV files into DataFrames.

df_2020 = pd.read_csv("athletic_sales_2020.csv")
df_2021 = pd.read_csv("athletic_sales_2021.csv")

In [28]:
# Display the 2020 sales DataFrame
display(df_2020)

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000.00,In-store
1,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,68,83,5644,2426.92,Online
2,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,75,275,206250,61875.00,Outlet
3,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,34,384,13056,6789.12,Outlet
4,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,53,83,4399,1407.68,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...
1292,West Gear,1128299,12/30/20,West,California,San Francisco,Women's Apparel,72,203,14616,3946.32,Online
1293,West Gear,1128299,12/30/20,West,California,San Francisco,Women's Apparel,80,700,560000,84000.00,Outlet
1294,Kohl's,1189833,12/30/20,Midwest,Minnesota,Minneapolis,Women's Street Footwear,41,119,4879,2878.61,Online
1295,Kohl's,1189833,12/30/20,Midwest,Minnesota,Minneapolis,Women's Street Footwear,45,475,213750,96187.50,Outlet
1296,West Gear,1128299,12/30/20,West,California,San Francisco,Women's Apparel,62,245,15190,2886.10,Outlet

In [29]:
# Display the 2021 sales DataFrame
display(df_2021)

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,65,750,487500,121875.00,Outlet
1,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,51,233,11883,3208.41,Outlet
2,Kohl's,1189833,1/1/21,Midwest,Montana,Billings,Men's Apparel,50,275,137500,82500.00,Outlet
3,Kohl's,1189833,1/1/21,Midwest,Montana,Billings,Men's Apparel,47,77,3619,2714.25,Online
4,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,64,225,14400,5184.00,Online
...,...,...,...,...,...,...,...,...,...,...,...,...
8341,Foot Locker,1185732,12/31/21,Northeast,Pennsylvania,Philadelphia,Men's Apparel,63,47,2961,1362.06,Online
8342,Foot Locker,1185732,12/31/21,Northeast,Pennsylvania,Philadelphia,Men's Apparel,46,56,2576,1004.64,Outlet
8343,Amazon,1185732,12/31/21,Northeast,Maine,Portland,Men's Apparel,52,36,1872,692.64,Online
8344,Amazon,1185732,12/31/21,Northeast,Maine,Portland,Men's Apparel,55,125,68750,17187.50,Outlet
8345,Foot Locker,1185732,12/31/21,Northeast,Pennsylvania,Philadelphia,Men's Apparel,70,175,122500,42875.00,Outlet

#### Check the data types of each DataFrame

In [30]:
# Check the 2020 sales data types.
dtypes = df_2020.dtypes
print(dtypes)

retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

In [31]:
# Check the 2021 sales data types.
dtypes = df_2021.dtypes
print(dtypes)

retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

#### Combine the sales data by rows.

In [32]:
# Combine the 2020 and 2021 sales DataFrames on the rows and reset the index.
combined_df = pd.concat([df_2020, df_2021], axis=0)
combined_df = combined_df.reset_index(drop=True)

In [33]:
# Check if any values are null.
null_counts = combined_df.isnull().sum()
print(null_counts)

retailer            0
retailer_id         0
invoice_date        0
region              0
state               0
city                0
product             0
price_per_unit      0
units_sold          0
total_sales         0
operating_profit    0
sales_method        0
dtype: int64

In [37]:
# Check the data type of each column
dtypes = combined_df.dtypes
print(dtypes)

retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

In [43]:
# Convert the "invoice_date" to a datetime datatype
combined_df['invoice_date'] = pd.to_datetime(combined_df['invoice_date'], infer_datetime_format=True)

<ipython-input-43-15bffe21a16f>:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  combined_df['invoice_date'] = pd.to_datetime(combined_df['invoice_date'], infer_datetime_format=True)

In [44]:
# Confirm that the "invoice_date" data type has been changed.
dtypes = combined_df.dtypes
print(dtypes)

retailer                    object
retailer_id                  int64
invoice_date        datetime64[ns]
region                      object
state                       object
city                        object
product                     object
price_per_unit               int64
units_sold                   int64
total_sales                  int64
operating_profit           float64
sales_method                object
dtype: object

### 2. Determine which Region Sold the Most Products

#### Using `groupby`

In [77]:
# Show the number products sold for region, state, and city.
count_nonzero = combined_df.groupby(['region', 'state', 'city'])['units_sold'].sum()
print(count_nonzero)

# Rename the sum to "Total_Products_Sold".
sum_column = count_nonzero.rename('Total_Products_Sold')

# Show the top 5 results.
top_5_results = sum_column.head(5)
display(top_5_results)

region     state           city
Midwest    Illinois        Chicago            25407
           Indiana         Indianapolis       26332
           Iowa            Des Moines         23446
           Kansas          Wichita            29463
           Michigan        Detroit            50095
           Minnesota       Minneapolis        20415
           Missouri        St. Louis          36404
           Montana         Billings           42713
           Nebraska        Omaha              19154
           North Dakota    Fargo              22781
           Ohio            Columbus           47781
           South Dakota    Sioux Falls        22973
           Wisconsin       Milwaukee          23950
Northeast  Connecticut     Hartford           34696
           Delaware        Wilmington         30275
           Maine           Portland           22410
           Maryland        Baltimore          20818
           Massachusetts   Boston             32895
           New Hampshire   Manchester         40812
           New Jersey      Newark             26540
           New York        Albany             57186
                           New York          111954
           Pennsylvania    Philadelphia       27662
           Rhode Island    Providence         27473
           Vermont         Burlington         38685
           West Virginia   Charleston         29873
South      Alabama         Birmingham         63327
           Arkansas        Little Rock        48468
           Louisiana       New Orleans        57615
           Mississippi     Jackson            56814
           Oklahoma        Oklahoma City      40459
           Tennessee       Knoxville          66077
           Texas           Dallas             69178
                           Houston            90322
Southeast  Florida         Miami              73135
                           Orlando            60295
           Georgia         Atlanta            56391
           Kentucky        Louisville         28664
           North Carolina  Charlotte          62936
           South Carolina  Charleston         72610
           Virginia        Richmond           52969
West       Alaska          Anchorage          30815
           Arizona         Phoenix            46919
           California      Los Angeles        76384
                           San Francisco      85478
           Colorado        Denver             41378
           Hawaii          Honolulu           40375
           Idaho           Boise              63827
           Nevada          Las Vegas          51831
           New Mexico      Albuquerque        52633
           Oregon          Portland           50536
           Utah            Salt Lake City     48548
           Washington      Seattle            46611
           Wyoming         Cheyenne           50228
Name: units_sold, dtype: int64

region   state     city
Midwest  Illinois  Chicago         25407
         Indiana   Indianapolis    26332
         Iowa      Des Moines      23446
         Kansas    Wichita         29463
         Michigan  Detroit         50095
Name: Total_Products_Sold, dtype: int64

#### Using `pivot_table`

In [76]:
# Show the number products sold for region, state, and city.

pivot_table = pd.pivot_table(combined_df, values='units_sold', index=['region', 'state', 'city'], aggfunc='sum')

# Rename the "units_sold" column to "Total_Products_Sold"
units_sold_column = pivot_table.rename(columns={'units_sold': 'Total_Products_Sold'})

# Show the top 5 results.
top_5_results = units_sold_column.head(5)
display(top_5_results)

                               Total_Products_Sold
region  state    city
Midwest Illinois Chicago                     25407
        Indiana  Indianapolis                26332
        Iowa     Des Moines                  23446
        Kansas   Wichita                     29463
        Michigan Detroit                     50095

### 3. Determine which Region had the Most Sales

#### Using `groupby`

In [78]:
# Show the total sales for the products sold for each region, state, and city.
groupbype_df = combined_df.groupby(['region', 'state', 'city'])
total_sales = groupbype_df['total_sales'].sum()

# Rename the "total_sales" column to "Total Sales"
total_sales = groupbype_df['total_sales'].sum().rename('Total Sales')

# Show the top 5 results.
top_5_results = total_sales.head(5)
display(top_5_results)

region   state     city
Midwest  Illinois  Chicago          9797488
         Indiana   Indianapolis     8836198
         Iowa      Des Moines       7424011
         Kansas    Wichita          9972864
         Michigan  Detroit         18625433
Name: Total Sales, dtype: int64

#### Using `pivot_table`

In [79]:
# Show the total sales for the products sold for each region, state, and city.
pivot_table = pd.pivot_table(combined_df, values='total_sales', index=['region', 'state', 'city'])



# Optional: Rename the "total_sales" column to "Total Sales"
pivot_table = pivot_table.rename(columns={'total_sales': 'Total Sales'})

# Show the top 5 results.
top_5_results = pivot_table.head(5)
display(top_5_results)

                                 Total Sales
region  state    city
Midwest Illinois Chicago        68038.111111
        Indiana  Indianapolis   61362.486111
        Iowa     Des Moines     51555.631944
        Kansas   Wichita        69256.000000
        Michigan Detroit       129343.284722

### 4. Determine which Retailer had the Most Sales

#### Using `groupby`

In [80]:
# Show the total sales for the products sold for each retailer, region, state, and city.
groupbype_df = combined_df.groupby(['retailer', 'region', 'state', 'city'])
total_sales = groupbype_df['total_sales'].sum()
# Rename the "total_sales" column to "Total Sales"
groupbype_df = groupbype_df['total_sales'].sum().rename('Total Sales')

# Show the top 5 results.
top_5_results = groupbype_df.head(5)
display(top_5_results)

retailer  region     state          city
Amazon    Midwest    Ohio           Columbus      16835873
          Northeast  Maine          Portland       8611395
                     Massachusetts  Boston         4193590
                     New Hampshire  Manchester    10077142
                     Vermont        Burlington    13380463
Name: Total Sales, dtype: int64

#### Using `pivot_table`

In [81]:
# Show the total sales for the products sold for each retailer, region, state, and city.

pivot_table = pd.pivot_table(combined_df, values='total_sales', index=['retailer', 'region', 'state', 'city'])

# Optional: Rename the "total_sales" column to "Total Sales"
pivot_table = pivot_table.rename(columns={'total_sales': 'Total Sales'})

# Show the top 5 results.
top_5_results = pivot_table.head(5)
display(top_5_results)

                                               Total Sales
retailer region    state         city
Amazon   Midwest   Ohio          Columbus    123793.183824
         Northeast Maine         Portland     63319.080882
                   Massachusetts Boston       63539.242424
                   New Hampshire Manchester   74645.496296
                   Vermont       Burlington   65590.504902

### 5. Determine which Retailer Sold the Most Women's Athletic Footwear

In [68]:
# Filter the sales data to get the women's athletic footwear sales data.
filtered_df = combined_df[combined_df['product'] == 'Women\'s Athletic Footwear']
display(filtered_df)

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
21,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,36,281,10116,3742.92,Outlet
22,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,41,247,10127,4658.42,Online
23,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45,850,382500,133875.00,In-store
26,West Gear,1128299,2020-01-05,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,45,300,135000,47250.00,Outlet
27,West Gear,1128299,2020-01-05,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,34,90,3060,1254.60,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...
9633,Foot Locker,1185732,2021-12-30,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,57,53,3021,1601.13,Online
9634,Foot Locker,1185732,2021-12-30,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,40,53,2120,954.00,Outlet
9635,Amazon,1185732,2021-12-30,Northeast,Maine,Portland,Women's Athletic Footwear,42,36,1512,680.40,Online
9636,Amazon,1185732,2021-12-30,Northeast,Maine,Portland,Women's Athletic Footwear,45,125,56250,16875.00,Outlet
9637,Foot Locker,1185732,2021-12-30,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,60,175,105000,42000.00,Outlet

#### Using `groupby`

In [82]:
# Show the total number of women's athletic footwear sold for each retailer, region, state, and city.
groupbype_df = filtered_df.groupby(['retailer', 'region', 'state', 'city'])
total_sales = groupbype_df['units_sold'].sum()

# Rename the "units_sold" column to "Womens_Footwear_Units_Sold"
groupbype_df = groupbype_df['units_sold'].sum().rename('Womens_Footwear_Units_Sold')

# Show the top 5 results.
top_5_results = groupbype_df.head(5)
display(top_5_results)

retailer  region     state          city
Amazon    Midwest    Ohio           Columbus      5801
          Northeast  Maine          Portland      1841
                     Massachusetts  Boston        1190
                     New Hampshire  Manchester    3109
                     Vermont        Burlington    4327
Name: Womens_Footwear_Units_Sold, dtype: int64

#### Using `pivot_table`

In [83]:
# Show the total number of women's athletic footwear sold for each retailer, region, state, and city.
pivot_table = pd.pivot_table(filtered_df, values='units_sold', index=['retailer', 'region', 'state', 'city'])

# Rename the "units_sold" column to "Womens_Footwear_Units_Sold"
pivot_table = pivot_table.rename(columns={'units_sold': 'Womens_Footwear_Units_Sold'})

# Show the top 5 results.
top_5_results = pivot_table.head(5)
display(top_5_results)

                                             Womens_Footwear_Units_Sold
retailer region    state         city
Amazon   Midwest   Ohio          Columbus                    263.681818
         Northeast Maine         Portland                     83.681818
                   Massachusetts Boston                      132.222222
                   New Hampshire Manchester                  129.541667
                   Vermont       Burlington                  120.194444

### 6. Determine the Day with the Most Women's Athletic Footwear Sales

In [71]:
# Create a pivot table with the 'invoice_date' column is the index, and the "total_sales" as the values.
pivot_table = pd.pivot_table(filtered_df, values='total_sales', index='invoice_date')

# Optional: Rename the "total_sales" column to "Total Sales"
pivot_table = pivot_table.rename(columns={'total_sales': 'Total Sales'})

# Show the table.
display(pivot_table)

                Total Sales
invoice_date
2020-01-04    134247.666667
2020-01-05     47267.000000
2020-01-11     43185.333333
2020-01-17     57671.000000
2020-01-22    129416.666667
...                     ...
2021-12-22     66802.000000
2021-12-23    134670.333333
2021-12-24     38177.000000
2021-12-25    105058.333333
2021-12-30     33580.600000

[355 rows x 1 columns]

In [73]:
# Resample the pivot table into daily bins, and get the total sales for each day.
pivot_table = pivot_table.resample('D').sum()

# Sort the resampled pivot table in descending order on "Total Sales".
pivot_table = pivot_table.sort_values(by='Total Sales', ascending=False)

display(pivot_table)

              Total Sales
invoice_date
2020-07-10       221360.0
2020-05-24       218768.0
2020-07-04       215343.0
2020-06-28       204687.5
2020-10-08       198699.0
...                   ...
2021-03-24            0.0
2020-08-12            0.0
2020-08-13            0.0
2021-03-18            0.0
2021-01-01            0.0

[727 rows x 1 columns]

### 7.  Determine the Week with the Most Women's Athletic Footwear Sales

In [74]:
# Resample the pivot table into weekly bins, and get the total sales for each week.
pivot_table = pivot_table.resample('W').sum()

# Sort the resampled pivot table in descending order on "Total Sales".
pivot_table = pivot_table.sort_values(by='Total Sales', ascending=False)

display(pivot_table)

                Total Sales
invoice_date
2021-06-13    552441.892857
2021-12-19    508094.310823
2021-12-12    495134.083333
2021-05-09    491505.308333
2021-12-05    485858.416667
...                     ...
2020-12-06     31400.500000
2020-12-20     30855.000000
2020-12-13     29458.000000
2020-11-22     26970.000000
2020-10-18         0.000000

[105 rows x 1 columns]